### ISSUE TITLE
topHoldersPercentOfTotalSupply() for bitcoin is empty

### ISSUE THREAD

**Issue by josefansinger** [santiment/san-sdk#15]
`topHoldersPercentOfTotalSupply()` for `bitcoin` is empty. Works for `santiment` and `ethereum`  though for different time frames (full year vs. last three months).

```
{
  topHoldersPercentOfTotalSupply(
    slug: "bitcoin"
    from: "2019-01-01T00:00:00Z"
    to: "2020-01-01T00:00:00Z"
    interval: "1d"
    numberOfHolders: 100) {
      datetime
      inTopHoldersTotal
      outsideExchanges
      inExchanges
  }
}
```

**Comment by IvanIvanoff** [comment]
Currently, the top holders are available only for Ethereum and the tokens on ethereum (such as `santiment`). It is not immediately clear that this is the case. In order to fix such misunderstandings, we have started this page: https://academy.santiment.net/metrics/daily-active-addresses/#available-assets

In this case, it lists the assets we have the data for. This page is still not yet ready for the query you are using though, but we're working on improving it.

**Comment by josefansinger** [comment]
@IvanIvanoff Thanks. Please notify me once a `topHoldersPercentOfTotalSupply()` `available-assets` API call is available.

**Comment by IvanIvanoff** [comment]
@josefansinger Currently we have this API:
https://tinyurl.com/thpapu6 (you can ctrl+click on the field for description). 
The `availableMetrics` is the union of those two: https://tinyurl.com/ukjgx2n (one is queried with `timeseriesData` and one - with `histogramData`). For example here you can see that `bitcoin` does not have `topHolders..` query listed.

There are known issues with this API currently (mainly the available metrics), mainly that it includes some metrics that are not really available. This issue is in the dev pipeline and is expected to be fixed this or next week.
