### ISSUE TITLE
feature request: extend devActivity to projects hosted on GitLab

### ISSUE THREAD

**Issue by josefansinger** [santiment/san-sdk#16]
Projects such as `tezos` and `siacoin` have moved their development from GitHub to GitLab. Consequently, their reported development activity has dropped. Can you please add GitLab to your coverage?

Medium term, can you provide a complete list of projects where `devActivity` is known to be misleading?

**Comment by IvanIvanoff** [comment]
GitLab integration will be done, though I cannot promise when.

Can you elaborate on the second part - how do you define if devActivity is misleading for a project?

**Comment by josefansinger** [comment]
@IvanIvanoff Right now, I have to google every project by hand if they might have moved from GitHub to another development platform. Do you have a (complete) list?

As advised by Max, I am replacing `devActivity()` by `getMetric(metric:"dev_activity")`. IMO, the call below should not include `tezos`, `siacoin` etc. since the API call does not reflect how much the project is under development. 
```
{
  getMetric(metric: "dev_activity"){
    metadata{
      availableSlugs
    }
  }
}
```

**Comment by IvanIvanoff** [comment]
> Right now, I have to google every project by hand if they might have moved from GitHub to another development platform. Do you have a (complete) list?

I see no way to do this rather than manually checking - I am not sure it's possible to programmatically check.

> IMO, the call below should not include tezos, siacoin [...]

I would have to disagree with this as by removing it we would lose historical data, which in some cases can be important. A similar example is why we're not removing the ethereum spent metric if the project no longer is ethereum-based but moved to their own chain: EOS raised a lot of ether and spent a lot of ether - we do not want to use the historical data in this case either: 
![image](https://user-images.githubusercontent.com/6518376/74726245-cc2edb80-5247-11ea-8219-db83e0008af0.png)


The best case scenario would be to implement gitlab activity and let the `devActivity` metric combine both github and gitlab data to have a full result.

**Comment by josefansinger** [comment]
@IvanIvanoff Sounds good. 👍

**Comment by IvanIvanoff** [comment]
Adding gitlab dev activity to the API will happen through the sanbase repo. I've opened an issue there so you can follow when the work starts and how it progresses there: https://github.com/santiment/sanbase2/issues/1784

The topic would be raised on the next planning but it could be postponed due to more urgent tasks or not enough developer time, will update on Friday.
