### ISSUE TITLE
availableSince for daily_active_addresses incorrect

### ISSUE THREAD

**Issue by josefansinger** [santiment/san-sdk#18]
Let us consider `bitcoin`. The metric `daily_active_addresses` is meant to be available since [`2009-01-09`](https://api.santiment.net/graphiql?query=%7B%0A%20%20getMetric(metric%3A%20%22daily_active_addresses%22)%7B%0A%20%20%20%20availableSince(slug%3A%20%22bitcoin%22)%0A%20%20%7D%0A%7D%0A&variables=). But anything before `2012-03-01` [fails](https://api.santiment.net/graphiql?query=%7B%0A%20%20getMetric(metric%3A%22daily_active_addresses%22)%20%7B%0A%20%20%20%20timeseriesData(slug%3A%22bitcoin%22%2C%20from%3A%222012-03-01T00%3A00%3A00Z%22%2C%20to%3A%222020-02-02T00%3A00%3A00Z%22%2C%20interval%3A%221d%22%2C%20aggregation%3ASUM)%20%7B%0A%20%20%20%20%20%20datetime%0A%20%20%20%20%20%20value%0A%20%20%20%20%7D%0A%20%20%7D%0A%7D%0A).

**Comment by valo** [comment]
@josefansinger I think you need a PRO subscription to get such old data. What is the error you get?

**Comment by IvanIvanoff** [comment]
Can you share your error? It should be a complexity error - asking for too big interval that will return too much data in a single request can fail.

The daily active addresses are free (no plans needed) and there is data:
![image](https://user-images.githubusercontent.com/6518376/74737158-f63ec880-525c-11ea-8147-ee862cb717d1.png)

**Comment by josefansinger** [comment]
@IvanIvanoff Yep, correct. Complexity error.

Can you take the complexity error into account when returning `availableSince`?

```
{
  "errors": [
    {
      "locations": [
        {
          "column": 5,
          "line": 3
        }
      ],
      "message": "Field timeseriesData is too complex: complexity is 29000 and maximum is 20000"
    },
    {
      "locations": [
        {
          "column": 3,
          "line": 2
        }
      ],
      "message": "Field getMetric is too complex: complexity is 29001 and maximum is 20000"
    },
    {
      "locations": [
        {
          "column": 1,
          "line": 1
        }
      ],
      "message": "Operation is too complex: complexity is 29001 and maximum is 20000"
    }
  ]
}
```

**Comment by IvanIvanoff** [comment]
Fetching big intervals returning many data points are rejected without execution. Reason is that such queries could put a lot of pressure on the database - one such query could scan/aggregate huge amount of data. A few solutions are:
1.) Break the request into a few smaller ones;
2.) Obtain a non-free plan - they have increased complexity limits which allow you to fetch more data with single queries;

Note: `availableSince` shows the first datetime that *could* be fetched if you have access to it. For example `circulation_1d` would again show it's available since 2009, but free plan cannot access it.

To see what restrictions are applied to the currently logged in user you can execute [this](https://api.santiment.net/graphiql?query=%7B%0A%20%20getAccessRestrictions%7B%0A%20%20%20%20name%0A%20%20%20%20type%0A%20%20%20%20isRestricted%0A%20%20%20%20restrictedFrom%0A%20%20%20%20restrictedTo%0A%20%20%7D%0A%7D)

**Comment by josefansinger** [comment]
@IvanIvanoff I understand. Thank you.
I will check for both `isRestricted` and `availableSince`.

Amazing that you can provide such old data. Very nice!
