### ISSUE TITLE
gap in MKR prices

### ISSUE THREAD

**Issue by josefansinger** [santiment/san-sdk#20]
The metric `daily_avg_price_usd` for the slug `maker` is available since [2017-01-29](https://api.santiment.net/graphiql?query=%7B%0A%20%20getMetric(metric%3A%20%22daily_avg_price_usd%22)%7B%0A%20%20%20%20availableSince(slug%3A%20%22maker%22)%0A%20%20%7D%0A%7D%0A). But you report [no price data](https://api.santiment.net/graphiql?query=%7B%0A%09getMetric(metric%3A%22daily_avg_price_usd%22)%20%7B%0A%20%20%20%20timeseriesData(slug%3A%22maker%22%2C%20from%3A%222017-01-29T00%3A00%3A00Z%22%2C%20to%3A%222018-09-01T00%3A00%3A00Z%22%2C%20interval%3A%221d%22%2C%20aggregation%3ASUM)%20%7B%0A%20%20%20%20%20%20datetime%0A%20%20%20%20%20%20value%0A%20%20%20%20%7D%0A%20%20%7D%0A%7D%0A) for the first months. Would it be better to report 2018-05-30 as `availableSince` when `MKR` did hit the exchanges?

**Comment by IvanIvanoff** [comment]
Our pricing data comes from coinmarketcap and there's gap in the maker prices there, too, that's where the gap comes from:
![image](https://user-images.githubusercontent.com/6518376/75233213-2dfbc200-57c1-11ea-9630-44748110a1ff.png)
![image](https://user-images.githubusercontent.com/6518376/75233234-37852a00-57c1-11ea-8d58-e75ad52c66f0.png)

Maybe 21 November 2017 is a better availableSince, otherwise 7 months of data?

**Comment by josefansinger** [comment]
On `2017-11-21` your reported price is [zero](https://api.santiment.net/graphiql?query=%7B%0A%09getMetric(metric%3A%22daily_avg_price_usd%22)%20%7B%0A%20%20%20%20timeseriesData(slug%3A%22maker%22%2C%20from%3A%222017-01-29T00%3A00%3A00Z%22%2C%20to%3A%222018-09-01T00%3A00%3A00Z%22%2C%20interval%3A%221d%22%2C%20aggregation%3ASUM)%20%7B%0A%20%20%20%20%20%20datetime%0A%20%20%20%20%20%20value%0A%20%20%20%20%7D%0A%20%20%7D%0A%7D%0A). Not what I can see at [coinmarketcap](https://coinmarketcap.com/currencies/maker/).
Then `2017-11-21` would be a good `availableSince`.

FYI, right in the middle on `2018-09-17` there is also a missing price point which is reported in coinmarketcap.

**Comment by IvanIvanoff** [comment]
I've scheduled a price refill for that time, let's wait some time to see if it's able to get the missing prices. Would take some time as there are thousands of projects and a very low rate limit to cmc.

**Comment by IvanIvanoff** [comment]
@josefansinger now I actually saw that you're using the `daily_avg_price_usd` metric instead of `price_usd`. The price is available, check [this](https://api.santiment.net/graphiql?query=%7B%0A%09getMetric(metric%3A%22price_usd%22)%20%7B%0A%20%20%20%20timeseriesData(slug%3A%22maker%22%2C%20from%3A%222017-11-21T00%3A00%3A00Z%22%2C%20to%3A%222018-05-08T00%3A00%3A00Z%22%2C%20interval%3A%221d%22%2C%20aggregation%3ALAST)%20%7B%0A%20%20%20%20%20%20datetime%0A%20%20%20%20%20%20value%0A%20%20%20%20%7D%0A%20%20%7D%0A%7D%0A) out.

The `daily_avg_price_usd` is something that should be deprecated from the API because of two reasons:
- It is an old metric that was introduced before `price_usd` and it cannot be easily recalcualted due to internal/dev specifics;
- It is daily, while `price_usd` is available per 5m and you can aggregate it however you want (as some people prefer average, while other prefer closing price)

PS: There are still some gaps that exist in coinmarketcap but we have not data to fill them, so only the `availableSince` field change should be addressed

**Comment by josefansinger** [comment]
@IvanIvanoff Thank you.

I am now calling `price_usd`, `volume_usd`, `daily_price_low_usd`, `daily_price_high_usd`, `daily_price_opening_usd` and `daily_price_closing_usd`.

Any of them deprecated?
Are `historyPrice()` and `ohlc()` deprecated?

**Comment by josefansinger** [comment]
If the `availableSince` field still needs to be addressed, shouldn't we reopen the issue?

**Comment by IvanIvanoff** [comment]
Let's create a separate issue as this one is `gap in MKR prices`.

> I am now calling price_usd, volume_usd, daily_price_low_usd, daily_price_high_usd, daily_price_opening_usd and daily_price_closing_usd

With `price_usd`/`volume_usd`/`marketcap_usd` + aggregation you can fetch all of the `daily_*` metrics.
For example:
- `daily_price_low_usd` = `price_usd` with `interval: "1d"` and `aggregation: MIN`
- `daily_price_close_usd` = `price_usd` with `interval: "1d"` and `aggregation: LAST`
- etc.

`high` can be achieved with `MAX` aggregation and `open` can be achieved with `FIRST` aggregation.

All of the following are to be deprecated as a better version of them is available:
- daily_avg_marketcap_usd
- daily_avg_price_usd
- daily_closing_marketcap_usd
- daily_closing_price_usd
- daily_high_price_usd
- daily_low_price_usd
- daily_opening_price_usd
- daily_trading_volume_usd


PS: https://github.com/santiment/san-sdk/issues/21 (Discussion only for availableSince)

**Comment by josefansinger** [comment]
Ah, ok. Opening = `FIRST`. Closing = `LAST`.

Then this issue can remain closed.

**Comment by IvanIvanoff** [comment]
You can explore all available aggregations per metric [like this](https://api.santiment.net/graphiql?query=%7B%0A%20%20getMetric(metric%3A%20%22price_usd%22)%7B%0A%20%20%20%20metadata%7B%0A%20%20%20%20%20%20availableAggregations%0A%20%20%20%20%7D%0A%20%20%7D%0A%7D)
