### ISSUE TITLE
availableSince fails

### ISSUE THREAD

**Issue by josefansinger** [santiment/san-sdk#23]
According to [this](https://api.santiment.net/graphiql?query=%7B%0A%20%20projectBySlug(slug%3A%22bitcoin%22)%20%7B%0A%20%20%20%20availableMetrics%0A%20%20%7D%0A%7D%0A) the `dev_activity` metric is available for `bitcoin`. But the [`availableSince`](https://api.santiment.net/graphiql?query=%7B%0A%20%20%20%20getMetric(metric%3A%22dev_activity%22)%20%7B%0A%20%20%20%20%20%20availableSince(slug%3A%20%22bitcoin%22)%0A%20%20%20%20%7D%0A%7D) call fails with `Internal server error`.

```
{
    getMetric(metric:"dev_activity") {
      availableSince(slug: "bitcoin")
    }
}
```

**Comment by josefansinger** [comment]
Same for `social_volume_total` and `bitcoin` or `ethereum`.

**Comment by IvanIvanoff** [comment]
Around 1 hour ago we had to replace some AWS nodes because they were in a bad state.
Both metrics seem to work now
![image](https://user-images.githubusercontent.com/6518376/76072054-f7cbf880-5f9f-11ea-9ad6-5bc1bee2db97.png)
![image](https://user-images.githubusercontent.com/6518376/76072155-21851f80-5fa0-11ea-81c9-a7155d2d6e1a.png)

**Comment by josefansinger** [comment]
Yep, working again. Thanks for the quick reply @IvanIvanoff.

**Comment by josefansinger** [comment]
<img width="1109" alt="Screenshot 2020-03-06 at 11 13 39" src="https://user-images.githubusercontent.com/59919615/76074397-943fcc00-5f9b-11ea-82d1-275d4faad06f.png">
Still not stable. Sorry.

**Comment by IvanIvanoff** [comment]
The issue is fixed here: https://github.com/santiment/sanbase2/pull/1822
The fix will be shipped to production today.

One note for the social `availableSince` - it is not as precise as the other on-chain/price/dev data. Best we can do is to return the first datetime for which we have data in a given source (telegram/reddit/etc.)

First mention of the project should not be taken into account in my opinion - many crypto projects have a commonly (or not so) used word in their ticker/name/slug - `san`, `data`, `link`, `dash`, etc. etc.

**Comment by josefansinger** [comment]
@IvanIvanoff Thank you. I will test `availableSince` next week.

**Comment by josefansinger** [comment]
I tried to get `social_volume_total` for `ethereum` for `2015-08-07` to `2020-03-06`. But get only `2016-06-10` to `2018-07-06`. My API key was upgraded to Pro (according to Max).

Why this limitation? Even in the GraphiQL interface I get more recent data.

**Comment by josefansinger** [comment]
@IvanIvanoff Just a suggestion: Can you please return a datapoint for each of the dates in the time frame `from` to `to`? If no data are available or the data plan does not allow access, please return `NA`. That would avoid post-processing from the client side and I would not need `availableSince` at all.

**Comment by IvanIvanoff** [comment]
`Can you please return a datapoint for each of the dates in the time frame from to to?`
I've been requesting the same behavior from the team implementing the social metrics.

cc @ipranovich any advances on the problem?

**Comment by ipranovich** [comment]
@IvanIvanoff it has to be fixed from python api side. 
 Preparing PR for it right now.

**Comment by josefansinger** [comment]
@ipranovich FYI, I access the GraphQL API via `ghql` from R not Python.
Thanks for addressing this issue!

**Comment by IvanIvanoff** [comment]
`python api side` here means the internal python service for which the graphql API is a proxy to, nothing in the client code should change (your R code)

**Comment by IvanIvanoff** [comment]
availableSince API no longer returns errors.


```
I tried to get social_volume_total for ethereum for 2015-08-07 to 2020-03-06. But get only 2016-06-10 to 2018-07-06. My API key was upgraded to Pro (according to Max).

Why this limitation? Even in the GraphiQL interface, I get more recent data.
```
The reason is that the API currently does not `return a data point for each of the dates in the time frame from to to` (as you requested). This leads to all sources returned data to not be of equal length and they're not properly combined.

**Comment by josefansinger** [comment]
@IvanIvanoff Thanks for the `availableSince` fix.
